### ISSUE TITLE
 Error: Typescript compilation failed

### ISSUE THREAD

**Issue by Homey4Osty** [evenh/net.evenh.tydom#7]
Hello,
i tried to install the latest vision on my Athom Homey 2023 Pro (SW-Version: 10.1.0). But the installation failed.

Error log:
PS C:\Users\carst\OneDrive\Dokumente\GitHub\net.evenh.tydom> homey app install
✓ Pre-processing app...
Added Driver `light`
Added Driver `thermostat`
Added Discovery Strategy `tydom1`
✓ Typescript detected. Compiling...
× Error occurred during while running tsc
app.ts(32,11): error TS2451: Cannot redeclare block-scoped variable 'logger'.
app.ts(33,11): error TS2451: Cannot redeclare block-scoped variable 'logger'.

× Error: Typescript compilation failed.
    at App.transpileToTypescript (C:\Users\carst\AppData\Roaming\npm\node_modules\homey\lib\App.js:91:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.preprocess (C:\Users\carst\AppData\Roaming\npm\node_modules\homey\lib\App.js:833:7)
    at async App.install (C:\Users\carst\AppData\Roaming\npm\node_modules\homey\lib\App.js:767:7)
    at async exports.handler (C:\Users\carst\AppData\Roaming\npm\node_modules\homey\bin\cmds\app\install.js:25:5)

Any ideas what's going wrong?

Thanks a lot. Gratings Osty

**Comment by evenh** [comment]
I don't have a Athom Homey 2023 to test with, but it runs fine on my older Homey Pro with node v16.18.1.  What version of node do you run?

Also, this project is still very rough around the edges (at least for now). Trying to find some time to improve it.

**Comment by Homey4Osty** [comment]
Then you have "the old" homey? 
I'm running on my HomeyPro2023 (https://homey.app/de-de/homey-pro/) the current software-vision (10.1.0) and the version (that was the latest version i found) of your sw:
  "devDependencies": {
    "@tsconfig/node16": "^16.1.0",
    "@types/homey": "npm:homey-apps-sdk-v3-types@^0.3.4",
    "@types/lodash": "^4.14.192",
    "@types/node": "^18.15.10",
    "@typescript-eslint/eslint-plugin": "^5.35.1",
    "@typescript-eslint/parser": "^5.35.1",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint": "^8.34.0",
    "prettier": "^2.8.4",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-sort-imports-es6-autofix": "0.6.0",
    "typescript": "^4.9.5"

Node.js is at v20.6.0

Thanks.

**Comment by Homey4Osty** [comment]
Request no longer relevant
